### ISSUE TITLE
Unable to use "placeholder" plugin with @ckeditor/ckeditor5-build-decoupled-document

### ISSUE THREAD

**Issue by thegauravsharma** [kiruh/ckeditor5-placeholder#2]
![image](https://user-images.githubusercontent.com/21969105/86764839-01f12700-c066-11ea-807a-77087ad0ac88.png)

Hi,

I am trying implement the **placeholder** plugin with **@ckeditor/ckeditor5-build-decoupled-document** however, getting following error and unable to resolve it. 

`ERROR Error: Uncaught (in promise): CKEditorError: **ckeditor-duplicated-modules**: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules`

**Editor I'm using:** 
https://www.npmjs.com/package/@ckeditor/ckeditor5-build-decoupled-document

Can you please fix it or provide the solution for the same?

Thanks,

Gaurav Sharma

**Comment by kiruh** [comment]
Fixed in [v1.0.4](https://github.com/kiruh/ckeditor5-placeholder/releases/tag/v1.0.4)

**Comment by thegauravsharma** [comment]
Thanks 👍
