### ISSUE TITLE
Issue using Placeholder with a DecoupledEditor

### ISSUE THREAD

**Issue by chiruko** [kiruh/ckeditor5-placeholder#4]
Hello there,

I have the very same issue someone has written last month. I'm using the DecoupledEditor and when I try to add the plugin, I get this error : 

ckeditorerror.js:66 Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

    at Module../node_modules/@ckeditor/ckeditor5-core/node_modules/@ckeditor/ckeditor5-utils/src/version.js 
    at __webpack_require__
    at Module../node_modules/@ckeditor/ckeditor5-core/node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js
    at __webpack_require__ 
    at Module../node_modules/@ckeditor/ckeditor5-core/node_modules/@ckeditor/ckeditor5-utils/src/observablemixin.js
    at __webpack_require__ 
    at Module../node_modules/@ckeditor/ckeditor5-core/src/plugin.js
    at __webpack_require__ 
    at Module../node_modules/ckeditor5-placeholder/src/placeholder.js
    at __webpack_require__

I use TypeScript for my app.
Could you help me please ?

Best regards,
Chiruko.

**Comment by ahtashamabbasse** [comment]
I'm getting the same error. is there any workaround?

**Comment by ahtashamabbasse** [comment]
@chiruko is this issue fixed?

**Comment by lucabecchetti** [comment]
any news???

**Comment by chiruko** [comment]
Hello, I had to download the DecoupledEditor folder (ckeditor5-build-decoupled-document) where I was able to insert my placeholder plugin folder and import my plugin without any trouble.

This is my ckeditor.js :

`/**
 * @license Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

// The editor creator to use.
import DecoupledEditorBase from '@ckeditor/ckeditor5-editor-decoupled/src/decouplededitor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import FontSize from '@ckeditor/ckeditor5-font/src/fontsize';
import FontFamily from '@ckeditor/ckeditor5-font/src/fontfamily';
import FontColor from '@ckeditor/ckeditor5-font/src/fontcolor';
import FontBackgroundColor from '@ckeditor/ckeditor5-font/src/fontbackgroundcolor';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PasteFromOffice from '@ckeditor/ckeditor5-paste-from-office/src/pastefromoffice';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';
import Placeholder from "../placeholder";

export default class DecoupledEditor extends DecoupledEditorBase {}

// Plugins to include in the build.
DecoupledEditor.builtinPlugins = [
	Essentials,
	Alignment,
	FontSize,
	FontFamily,
	FontColor,
	FontBackgroundColor,
	UploadAdapter,
	Autoformat,
	Bold,
	Italic,
	Strikethrough,
	Underline,
	BlockQuote,
	CKFinder,
	Heading,
	Indent,
	IndentBlock,
	Link,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	TextTransformation,
	Placeholder
];

// Editor configuration.
DecoupledEditor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'fontfamily',
			'fontsize',
			'fontColor',
			'fontBackgroundColor',
			'|',
			'bold',
			'italic',
			'underline',
			'strikethrough',
			'|',
			'alignment',
			'|',
			'numberedList',
			'bulletedList',
			'|',
			'indent',
			'outdent',
			'|',
			'blockquote',
			'|',
			'undo',
			'redo'
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	// This value must be kept in sync with the language defined in webpack.config.js.
	language: 'fr'
};`
![image](https://user-images.githubusercontent.com/47862135/150111564-df2908df-8de0-4c84-ad57-00edda25baa7.png)

**Comment by lucabecchetti** [comment]
How do you import the build?

**Comment by kiruh** [comment]
@chiruko you managed to configure placeholder plugin, right?

**Comment by lucabecchetti** [comment]
Yes, I want to add my custom plugin, I build a custom version using online build, but I'm not able to import as:

`//@ts-ignore
import Editor  from "../../../js/ckeditor5-31.1.0";`

I get an error like: export 'create' (imported as 'Editor') was not found in '../../../js/ckeditor

**Comment by kiruh** [comment]
> Yes, I want to add my custom plugin, I build a custom version using online build, but I'm not able to import as:
> 
> `//@ts-ignore import Editor from "../../../js/ckeditor5-31.1.0";`
> 
> I get an error like: export 'create' (imported as 'Editor') was not found in '../../../js/ckeditor

@lucabecchetti unfortunately, there is no online build of this plugin

**Comment by chiruko** [comment]
I did not install it through npm, I had to download the build (https://ckeditor.com/ckeditor-5/download/?null-addons=) to make it work and then I've put the build folder inside a folder. Then I could import the decoupled editor like this : 

`import DecoupledEditor from '@helper/ckeditor5-build-decoupled-document';`

You have to add the Placeholder plugin inside this build and import it in ckeditor.js.

@kiruh I did thanks to placeholderConfig inside the editorConfig.

I am sorry if it sounds a little confused, I've made it work a long time ago I try to remember everything guys but I'll do everything I can to help you!

**Comment by chiruko** [comment]
I downloaded the build from https://ckeditor.com/ckeditor-5/download/?null-addons=

**Comment by kiruh** [comment]
@chiruko where did you import placeholder plugin though? It seems that you can't make custom builds with plugins from npm

![image](https://user-images.githubusercontent.com/22396778/150124585-e36f8335-9b99-4ba3-a233-73d8532761dc.png)

**Comment by chiruko** [comment]
I've downloaded the plugin's zip and unzipped it inside my build. Then, I've imported it thanks to : `import Placeholder from "../placeholder";`

I did not use the online builder, I took a simple decoupled editor and I've added my plugin inside

**Comment by lucabecchetti** [comment]
1. I generated  custom editor from online builder
2. inside folder: npm install, npm install ckeditor5-placeholder
3. added placeholder to ckeditor.js
4. npm run build
5. copy build folder to my project
6. import with <script src="/ckeditor5-31.1.0/build/ckeditor.js"></script>
7. (window as any).DecoupledEditor.create ecc.. ecc...
and it works!

**Comment by chiruko** [comment]
Great! Let me know if you have trouble with the placeholders management

**Comment by kiruh** [comment]
@chiruko thank you for your help :)

**Comment by chiruko** [comment]
You're welcome! Have a nice day :)
