### ISSUE TITLE
Placeholder error with viewWriter

### ISSUE THREAD

**Issue by martonflori** [kiruh/ckeditor5-placeholder#5]
Hi there,

I have ran into an issue implementing the placeholder for ckeditor, I'd appreciate a little help. 
It's built with webpack, some of the imports I've dotted out for readability, the code is below:

```
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
import Placeholder from 'ckeditor5-placeholder';
...

export const createEditor = async (selector) => {
	let ckEditor;
	await ClassicEditor
		.create(document.querySelector(selector), {
			plugins: [
				... ,
				Placeholder
			],
			toolbar: [
                                ... ,
				'placeholder'
			],
			extraPlugins: [customUploadAdapterPlugin]
		})
		.then(editor => {
			console.log('Editor initialized');
			ckEditor = editor;
		})
		.catch(error => {
			console.error(error.stack);
		});
	return ckEditor;
}
```

Then later I'm using it like this: 
```
        const ckEditor = await import('../../../lib/ckeditor/ckeditor-webpack.js');
        const editor = await ckEditor.createEditor('#content');
```

And the error I'm getting when clicking on the placeholder prop: Uncaught TypeError: viewWriter.createContainerElement is not a function

![error](https://user-images.githubusercontent.com/60197149/95225258-e0860f80-07fb-11eb-901d-13c182d552cb.png)
Does anyone have an idea what could cause this?

Thanks in advance!

**Comment by martonx** [comment]
Hey, there is a bug in the code, at least with latest version of CkEditor 5.

In placeholderediting.js, you should add .writer to viewWriter. This is the fixed version

`conversion.for("editingDowncast").elementToElement({
      model: "placeholder",
      view: (modelItem, viewWriter) => {
        const widgetElement = createPlaceholderView(modelItem, viewWriter**.writer**);

        // Enable widget handling on placeholder element inside editing view.
        return toWidget(widgetElement, viewWriter**.writer**);
      },
});`
